### ISSUE TITLE
Feature Request:  Add ability to pass an error handler to happy_path

### ISSUE THREAD

**Issue by OvermindDL1** [vic/happy#2]
I have some very repeated else blocks in my phoenix application in happy_path, it would be awesome if I could instead of this:

``` elixir
def index(conn, _params) do
    happy_path do
      {:ok, {uid, _obj}} = verify_uid(uid)
      true = conn |> can?(index(%Perms.Auth.Permission{uid: uid, perm_name: :_}))
      query = from p in Permission,
              where: p.uid == ^uid
      conn
      |> render(:index,
        uid: uid,
        permissions: Repo.all(query),
        newable_permissions: MyServer.PermsLoader.get_all_perms(),
        )
    else
      {:error, :not_a_number}   -> bad_request(conn)
      {:error, :invalid_uid}    -> unprocessable_entity(conn)
      {:error, :atom_invalid}   -> bad_request(conn)
      {:error, :struct_invalid} -> unprocessable_entity(conn)
      {:error, err}             -> internal_server_error(conn)
      false                     -> unauthorized(conn)
    end
end
```

As like this instead:

``` elixir
def index(conn, _params) do
    happy_path &handle_happy_errors(conn, &1), do
      {:ok, {uid, _obj}} = verify_uid(uid)
      true = conn |> can?(index(%Perms.Auth.Permission{uid: uid, perm_name: :_}))
      query = from p in Permission,
              where: p.uid == ^uid
      conn
      |> render(:index,
        uid: uid,
        permissions: Repo.all(query),
        newable_permissions: MyServer.PermsLoader.get_all_perms(),
        )
    end
end

def handle_happy_errors(conn, err), do: conn |> other_stuff()
```

When I have 200+ functions, handling most of the same errors, an else path callback like that would be fantastic.  Would be nice if we could still specify an else path that is checked first before deferring to the callback if defined.  :-)

**Comment by OvermindDL1** [comment]
Although I could just call the function in the else I guess, but still trying to clean up the else block entirely since I have so very many of them.  :-)

**Comment by OvermindDL1** [comment]
Another passing thought.  ^.^

``` elixir
defhappy index(conn, _params) do
  {:ok, {uid, _obj}} = verify_uid(uid)
  true = conn |> can?(index(%Perms.Auth.Permission{uid: uid, perm_name: :_}))
  query = from p in Permission,
          where: p.uid == ^uid
  conn
  |> render(:index,
    uid: uid,
    permissions: Repo.all(query),
    newable_permissions: MyServer.PermsLoader.get_all_perms(),
    )
else
  err -> handle_errors(conn, err)
end

def handle_errors(conn, err), do: conn |> other_stuff()
```

**Comment by vic** [comment]
Yep, your last snippet would be the way to do it. Just handle the errors to a function and dispatch using pattern matching.

**Comment by OvermindDL1** [comment]
Any thought on the `defhappy` of the last snippet?  :-)

**Comment by vic** [comment]
Hey @OvermindDL1 

So I finally got your point on what you were trying to do. I added this new feature: _support for common error handler_ if you give it as first argument to `happy_path`. I've updated the readme and released a new version.

https://github.com/vic/happy#sharing-common-error-handling-code

**Comment by OvermindDL1** [comment]
Awesome!  Looks perfect; that and tags both continue to make happy_path more readable and thus better to code with then the new 'with/else' construct in Elixir 1.3.  Thanks!
