### ISSUE TITLE
`happy_path` spams warnings

### ISSUE THREAD

**Issue by OvermindDL1** [vic/happy#3]
When using `happy_path` the compiler spams warnings about:

``` elixir
web/controllers/auth/permissions_controller.ex:18: warning: this clause cannot match because a previous clause at line 18 always matches
```

Probably in the macro need to add a test for if the match, such as `perm = struct_name |> Map.from_struct` is unconditional, then to not emit the case for it?

**Comment by vic** [comment]
Could you share a little snippet of a whole `happy_path` block that produces this warning? Having it would help adding a test case and fix for it.

**Comment by OvermindDL1** [comment]
A simple case would just be an unconditional match, like this:

``` elixir
def index(conn, _params) do
    happy_path do
      # Snip other setup
      query = from p in Permission,
              where: p.uid == ^uid
      # Snip operating on query
    end
end
```

Where the query is there is just simple assignment matching, changing it to be:

``` elixir
def index(conn, _params) do
    happy_path do
      # Snip other setup
      %{} = query = from p in Permission,
              where: p.uid == ^uid
      # Snip operating on query
    end
end
```

Quiets the warning since it is actually testing 'something' about the match, and is what I've been doing so far, but it makes it surprisingly harder to read when you have 20 or so lines with 1 or 3 of those little warning silencer matches.  :-)

**Comment by OvermindDL1** [comment]
A simplified test-case would be

``` elixir
  test "This should not cause a warning at compilation" do
    happy_path do
      ok = %{}
      IO.inspect ok
    end
  end
```

The test passes, since I am not really testing anything at run-time, but at compile-time it causes this warning:

``` elixir
test/test_happy_test.exs:8: warning: this clause cannot match because a previous clause at line 8 always matches
```

**Comment by vic** [comment]
Hey @OvermindDL1 

Thanks for providing an example. You are right, just fixed this, from now on, when happy finds an expression like  `ok = %{}` where the left side is a simple pattern-match (like a variable assignment) it will be ignored altogether. That means that happy only rewrites things if you have patterns like `{:ok, stuff} = expr` or anything other than a simple assignment.

**Comment by vic** [comment]
I'm closing this, please open another issue if you find something weird with the new release. Thank you!
