### ISSUE TITLE
Warnings still

### ISSUE THREAD

**Issue by OvermindDL1** [vic/happy#4]
Still getting this same warning with version 2.0.1 (have cleaned project, cleaned the deps, redownloaded the deps, the lock file does show version 2.0.1, still the same warning):

``` elixir
warning: this clause cannot match because a previous clause at line 11 always matches
  web/controllers/users/users_controller.ex:18
```

For code like:

``` elixir
  def index(conn, _params) do
    happy_path do
      ok = %{}
      IO.inspect ok
    end
  end
```

I reduced it back down to the same case as before and it is causing the warning.  I did upgrade to Elixir 1.3.0 so unsure if that changed the matching somehow.  The previous line causing the issue, for note, was:

``` elixir
      users = Repo.all(Users)
```

**Comment by vic** [comment]
Hm.. there's a test for that exact case here:

https://github.com/vic/happy/blob/master/test/happy_path_test.exs#L428

What's the output if you try to expand the macro?

``` elixir
code = quote do
  happy_path do
      ok = %{}
      IO.inspect ok
    end
end

IO.puts Macro.to_string(Macro.expand(code, __ENV__))
```

**Comment by vic** [comment]
I'd be much nicer and I'd be greatful if you may clone this repo and try to add/change a test to reveal the bug :)

**Comment by OvermindDL1** [comment]
Forked and added a test-case here:
https://github.com/OvermindDL1/happy/blob/master/test/happy_path_test.exs#L513

I reliably and every time get the warning, as exampled:

``` elixir
$ mix test
warning: this clause cannot match because a previous clause at line 513 always matches
  test/happy_path_test.exs:513

...........%{}
...................

Finished in 0.1 seconds
30 tests, 0 failures

Randomized with seed 377000
```

:-)

**Comment by OvermindDL1** [comment]
I have no clue how to test warning output in a test case, so that is just the code that causes it, but it does cause it (at least in Elixir 1.3).

**Comment by OvermindDL1** [comment]
Oh, and expanding the macro generates exactly what I expect.  It may even be an Elixir bug perhaps?

**Comment by OvermindDL1** [comment]
Copy/paste failed me, the output was:

``` elixir
(
  ok = %{}
  IO.inspect(ok)
)
```

**Comment by vic** [comment]
Woa, I got it fixed :) could you try master or the new release `1.2.2` ? Thank you !

**Comment by OvermindDL1** [comment]
Just got to work, updating to 1.2.2 now.  :-)

``` elixir
$ mix do clean, compile
Compiling 42 files (.ex)
Generated <snip> app

```

Ooo, first clean build in a long time, awesome!  Thanks much!

Ah I see, it was just a too-tight matching of the case.  :-)
