### ISSUE TITLE
Tag error

### ISSUE THREAD

**Issue by OvermindDL1** [vic/happy#6]
This issue was happening in 1.2 and 1.3 as well.

I have this code (simplified from the actual code and since moved into a helper module but this is an error regardless):

``` elixir
    happy_path!(else: handle_error(conn)) do
      @param tag_id when is_integer(tag_id) = case Integer.parse(tag_param) do
        {tag_id, ""} -> tag_id
        _ -> get_tag_id(tag_param)
      end
    end
```

And when compiling it gives:

``` elixir
== Compilation error on file web/controllers/help/issue_controller.ex ==
** (ArgumentError) expected 0 or 1 argument for @param, got: 2
    (elixir) lib/kernel.ex:2381: Kernel.do_at/4
    (elixir) expanding macro: Kernel.@/1
    web/controllers/help/issue_controller.ex:77: MyServer.Help.IssueController.add_tag/2
    (elixir) expanding macro: Kernel.|>/2
    web/controllers/help/issue_controller.ex:73: MyServer.Help.IssueController.add_tag/2
    (elixir) expanding macro: Kernel.|>/2
    web/controllers/help/issue_controller.ex:73: MyServer.Help.IssueController.add_tag/2
    expanding macro: Happy.happy_path!/2
    web/controllers/help/issue_controller.ex:73: MyServer.Help.IssueController.add_tag/2
    (elixir) lib/kernel/parallel_compiler.ex:116: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

If I remove the `@param` tag it works.  If I remove the `when` clause then it works.  It only seems to happen when a tag and a `when` clause are used together like this.

And as always, `happy` is an awesome library!

**Comment by vic** [comment]
Hey, 

Made some tests and it seems your error comes from the fact that in Elixir syntax a `do` block has lower precedence and in your example, its being binded to the tag and not to the case expression, 
for example expanding the following code yields:

``` elixir
iex(2)> quote do
...(2)>   @foo x when is_nil(x) = case y do
...(2)>     :bar
...(2)>   end
...(2)> end |> Macro.to_string |> IO.puts

@foo(x when is_nil(x) = case(y)) do
  :bar
end
```

Thus, the compiler complains because `@foo` cannot be given two arguments, the second being a keyword with`[do: ....]`.

So if you really want to have that case, wrap it with parens `()` to make the block bind to it.

**Comment by vic** [comment]
Ok, just made some changes to happy so you dont need to explicitly wrap your right side case within parens. happy_path will now move the block to be part of the correct case for you.

**Comment by OvermindDL1** [comment]
Figured it was that.

And awesome!  Thanks much!
